function [fitresult, gof] = createFit(f_range, B_range, P)
%CREATEFIT(F_RANGE,B_RANGE,P)
%  Create a fit.
%
%  Data for 'Surface' fit:
%      X Input : f_range
%      Y Input : B_range
%      Z Output: P
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Dec-2022 13:34:14


%% Fit: 'Surface'.
[xData, yData, zData] = prepareSurfaceData( f_range, B_range, P );

% Set up fittype and options.
ft = fittype( 'k*x^a*y^b', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.260428644600092 0.940333711980278 0.547215529963803];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Surface' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Surface', 'P vs. f_range, B_range', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'f_range', 'Interpreter', 'none' );
ylabel( 'B_range', 'Interpreter', 'none' );
zlabel( 'P', 'Interpreter', 'none' );
grid on


