function [fitresult, gof] = createFit(x4, y4)
%CREATEFIT(X4,Y4)
%  Create a fit.
%
%  Data for '200mT' fit:
%      X Input : x4
%      Y Output: y4
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Dec-2022 10:40:45


%% Fit: '200mT'.
[xData, yData] = prepareCurveData( x4, y4 );

% Set up fittype and options.
ft = fittype( 'k*x^a*0.2^b', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.747489478402464 0.126820712754585 0.709364830858073];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', '200mT' );
h = plot( fitresult, xData, yData );
legend( h, 'y4 vs. x4', '200mT', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x4', 'Interpreter', 'none' );
ylabel( 'y4', 'Interpreter', 'none' );
grid on


