function [fitresult, gof] = createFit(x5, y5)
%CREATEFIT(X5,Y5)
%  Create a fit.
%
%  Data for '300mT' fit:
%      X Input : x5
%      Y Output: y5
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Dec-2022 10:46:13


%% Fit: '300mT'.
[xData, yData] = prepareCurveData( x5, y5 );

% Set up fittype and options.
ft = fittype( 'k*x^a*0.3^b', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.89883322382211 0.294754399637592 0.505957051665142];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', '300mT' );
h = plot( fitresult, xData, yData );
legend( h, 'y5 vs. x5', '300mT', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x5', 'Interpreter', 'none' );
ylabel( 'y5', 'Interpreter', 'none' );
grid on


