function [fitresult, gof] = createFit(x2, y2)
%CREATEFIT(X2,Y2)
%  Create a fit.
%
%  Data for '50mT' fit:
%      X Input : x2
%      Y Output: y2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Dec-2022 10:34:06


%% Fit: '50mT'.
[xData, yData] = prepareCurveData( x2, y2 );

% Set up fittype and options.
ft = fittype( 'k*x^a*0.05^b', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.0843065411551075 0.739014598693051 0.438744359656398];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', '50mT' );
h = plot( fitresult, xData, yData );
legend( h, 'y2 vs. x2', '50mT', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x2', 'Interpreter', 'none' );
ylabel( 'y2', 'Interpreter', 'none' );
grid on


