function [fitresult, gof] = createFit(x3, y3)
%CREATEFIT(X3,Y3)
%  Create a fit.
%
%  Data for '100mT' fit:
%      X Input : x3
%      Y Output: y3
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Dec-2022 10:37:55


%% Fit: '100mT'.
[xData, yData] = prepareCurveData( x3, y3 );

% Set up fittype and options.
ft = fittype( 'k*x^a*0.1^b', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.112145636748411 0.47831407362237 0.186872604554379];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', '100mT' );
h = plot( fitresult, xData, yData );
legend( h, 'y3 vs. x3', '100mT', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x3', 'Interpreter', 'none' );
ylabel( 'y3', 'Interpreter', 'none' );
grid on


